title: Lorenzo Minuz
description: Physics student | Tech Enthusiast | Lifelong Learner
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lm0516.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  LM0516

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Math Support
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Consenti a Jekyll di leggere i file nelle cartelle che iniziano con _
include: [_includes]